language: ruby
rvm:
  - 2.3.3
env:
  - DB=postgis
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database test_app_test' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d test_app_test
